theme: jekyll-theme-minimal
title: Hello!
description: Feel free to stalk my research with the info available in this website :)
logo: assets/profile.jpg
email: kidoshimomoto.e@aist.go.jp
linkedin: erica-shimomoto
researchgate: Erica-Kido-Shimomoto-2
